apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaTopic
metadata:
    name: temperature-sensor
    labels:
        strimzi.io/cluster: "kafka-cluster"
spec:
    partitions: 3
    replicas: 3
---
apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaTopic
metadata:
    name: lights
    labels:
        strimzi.io/cluster: "kafka-cluster"
spec:
    partitions: 3
    replicas: 3
